import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { FiltersEngine } from '@ghostery/adblocker';

/**
 * Scriptlets (ROADMAP 3.6, D-041): uBlock Origin's small page scripts that the ad lists attach to
 * sites (`youtube.com##+js(...)`), e.g. removing ad slots from YouTube's player data before the player
 * reads it. They must run in the page's own world before any page script, and web views have no IPC,
 * so main writes one preload file per app session with that app's scriptlets as literal code and
 * registers it on the session. At document start the file hands the code for the current site to the
 * main world via `contextBridge.executeInMainWorld` (not subject to the page's CSP) and does nothing
 * else: no IPC, nothing exposed. It only runs when "Block ads" is on for the view (`--aio-webapp`).
 */

/** Sites the Browser tile gets scriptlets for (it can go anywhere; files stay small). */
export const BROWSER_SCRIPTLET_SITES = ['youtube.com', 'twitch.tv'];

/** Scriptlets the ad lists give a site (checked on its www host; most rules cover the whole site). */
export function scriptletsFor(engine: FiltersEngine, site: string): string[] {
  const hostname = `www.${site}`;
  return engine.getCosmeticsFilters({
    url: `https://${hostname}/`,
    hostname,
    domain: site,
    getBaseRules: false,
    getRulesFromDOM: false,
    getRulesFromHostname: true,
    getInjectionRules: true,
    getExtendedRules: false,
  }).scripts;
}

/**
 * The preload source. Each site's scriptlets become one function body (each scriptlet in its own
 * function scope); the function's source is what `executeInMainWorld` runs in the page.
 */
export function buildScriptletPreload(sites: Record<string, string[]>): string {
  const entries = Object.entries(sites)
    .filter(([, scripts]) => scripts.length > 0)
    .map(([site, scripts]) => `  ${JSON.stringify(site)}: function () {\n${scripts.map((s) => `    try { (function () {\n${s}\n    })(); } catch (e) {}`).join('\n')}\n  }`);
  return `// Generated by AIO Space (main/privacy/scriptlets.ts). Do not edit: rewritten when the ad lists update.
const { contextBridge } = require('electron');
const arg = process.argv.find((a) => a.startsWith('--aio-webapp=')) || '';
const blockAds = arg.slice('--aio-webapp='.length).split(',')[3] === '1';
const sites = {
${entries.join(',\n')}
};
if (blockAds) {
  const host = location.hostname;
  for (const site of Object.keys(sites)) {
    if (host === site || host.endsWith('.' + site)) {
      try { contextBridge.executeInMainWorld({ func: sites[site] }); } catch (e) {}
      break;
    }
  }
}
`;
}

interface Registration {
  file: string;
  sites: string[];
}

/** One preload file per app session; rewritten when the lists change. */
export class ScriptletFiles {
  private readonly registered = new Map<string, Registration>();

  /**
   * @param siteScripts Extra page scripts for a site that replace the lists' scriptlets there
   *   (Twitch ad blocking, D-043); empty to use the lists.
   */
  constructor(
    private readonly dir: string,
    private readonly engine: () => FiltersEngine | undefined,
    private readonly siteScripts: (site: string) => string[] = () => [],
  ) {}

  /** Write the file for a session partition and return its path (for `registerPreloadScript`). */
  fileFor(partition: string, sites: string[]): string {
    const file = join(this.dir, `${partition.replace(/^persist:/, '').replace(/[^a-z0-9_-]/gi, '_')}.js`);
    this.registered.set(partition, { file, sites });
    this.write({ file, sites });
    return file;
  }

  /** The lists were updated: every session's file gets the new scriptlets (from its next page load). */
  refresh(): void {
    for (const reg of this.registered.values()) this.write(reg);
  }

  private write({ file, sites }: Registration): void {
    const engine = this.engine();
    const scripts: Record<string, string[]> = {};
    for (const site of sites) {
      const own = this.siteScripts(site);
      if (own.length) {
        scripts[site] = own; // e.g. a Twitch ad-blocking script: never combined with other Twitch rules
        continue;
      }
      try {
        scripts[site] = engine ? scriptletsFor(engine, site) : [];
      } catch {
        scripts[site] = [];
      }
    }
    mkdirSync(this.dir, { recursive: true });
    writeFileSync(file, buildScriptletPreload(scripts), { mode: 0o600 });
  }
}
